"""initial_schema_all_tables

Revision ID: 53106128a969
Revises: 
Create Date: 2026-03-03 23:20:06.603828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53106128a969'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('hiring_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dsa_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_design', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interview_format', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('behavioral', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scoring_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_blueprints_slug'), 'company_blueprints', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('leetcode_username', sa.String(length=100), nullable=True),
    sa.Column('kaggle_username', sa.String(length=100), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('college_tier', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('internship_count', sa.Integer(), nullable=True),
    sa.Column('available_months', sa.Integer(), nullable=True),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('resume_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('github_oauth_id', sa.String(length=100), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_oauth_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('agent_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('merged_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coaching_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_table('company_match_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=100), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_label', sa.String(length=50), nullable=True),
    sa.Column('weeks_away', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_slug'], ['company_blueprints.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_match_scores_company_slug'), 'company_match_scores', ['company_slug'], unique=False)
    op.create_index(op.f('ix_company_match_scores_user_id'), 'company_match_scores', ['user_id'], unique=False)
    op.create_table('platform_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_score', sa.Float(), nullable=True),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_scores_user_id'), 'platform_scores', ['user_id'], unique=False)
    op.create_table('user_roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=100), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('hours_per_day', sa.Integer(), nullable=True),
    sa.Column('weeks_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roadmaps_user_id'), 'user_roadmaps', ['user_id'], unique=False)
    op.create_table('user_skill_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=100), nullable=True),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Enum('BLOCKING', 'IMPORTANT', 'NICE_TO_HAVE', name='gappriority'), nullable=False),
    sa.Column('current_level', sa.Float(), nullable=True),
    sa.Column('required_level', sa.Float(), nullable=True),
    sa.Column('dependency_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_gaps_user_id'), 'user_skill_gaps', ['user_id'], unique=False)
    op.create_table('user_target_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_slug'], ['company_blueprints.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_target_companies_user_id'), 'user_target_companies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_target_companies_user_id'), table_name='user_target_companies')
    op.drop_table('user_target_companies')
    op.drop_index(op.f('ix_user_skill_gaps_user_id'), table_name='user_skill_gaps')
    op.drop_table('user_skill_gaps')
    op.drop_index(op.f('ix_user_roadmaps_user_id'), table_name='user_roadmaps')
    op.drop_table('user_roadmaps')
    op.drop_index(op.f('ix_platform_scores_user_id'), table_name='platform_scores')
    op.drop_table('platform_scores')
    op.drop_index(op.f('ix_company_match_scores_user_id'), table_name='company_match_scores')
    op.drop_index(op.f('ix_company_match_scores_company_slug'), table_name='company_match_scores')
    op.drop_table('company_match_scores')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_company_blueprints_slug'), table_name='company_blueprints')
    op.drop_table('company_blueprints')
    # ### end Alembic commands ###
